//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinYin4N.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinYin4N.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;pinyin_gwoyeu_mapping&gt;
        /// &lt;item&gt;
        ///  &lt;Hanyu&gt;a&lt;/Hanyu&gt;
        ///  &lt;Gwoyeu_I&gt;a&lt;/Gwoyeu_I&gt;
        ///  &lt;Gwoyeu_II&gt;ar&lt;/Gwoyeu_II&gt;
        ///  &lt;Gwoyeu_III&gt;aa&lt;/Gwoyeu_III&gt;
        ///  &lt;Gwoyeu_IV&gt;ah&lt;/Gwoyeu_IV&gt;
        ///  &lt;Gwoyeu_V&gt;.a&lt;/Gwoyeu_V&gt;
        /// &lt;/item&gt;
        /// &lt;item&gt;
        ///  &lt;Hanyu&gt;ai&lt;/Hanyu&gt;
        ///  &lt;Gwoyeu_I&gt;ai&lt;/Gwoyeu_I&gt;
        ///  &lt;Gwoyeu_II&gt;air&lt;/Gwoyeu_II&gt;
        ///  &lt;Gwoyeu_III&gt;ae&lt;/Gwoyeu_III&gt;
        ///  &lt;Gwoyeu_IV&gt;ay&lt;/Gwoyeu_IV&gt;
        ///  &lt;Gwoyeu_V&gt;.ai&lt;/Gwoyeu_V&gt;
        /// &lt;/item&gt;
        /// &lt;item&gt;
        ///  &lt;Hanyu&gt;an&lt;/Hanyu&gt;
        ///  &lt;Gwoyeu_I&gt;an&lt;/Gwoyeu_I&gt;
        ///  &lt;Gwoyeu_II&gt;arn&lt;/Gwoyeu_II&gt;
        ///  &lt;Gwoyeu_I [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string pinyin_gwoyeu_mapping {
            get {
                return ResourceManager.GetString("pinyin_gwoyeu_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;pinyin_mapping&gt;
        /// &lt;item&gt;
        ///  &lt;Hanyu&gt;a&lt;/Hanyu&gt;
        ///  &lt;Wade&gt;a&lt;/Wade&gt;
        ///  &lt;MPSII&gt;a&lt;/MPSII&gt;
        ///  &lt;Yale&gt;a&lt;/Yale&gt;
        ///  &lt;Tongyong&gt;a&lt;/Tongyong&gt;
        /// &lt;/item&gt;
        /// &lt;item&gt;
        ///  &lt;Hanyu&gt;ai&lt;/Hanyu&gt;
        ///  &lt;Wade&gt;ai&lt;/Wade&gt;
        ///  &lt;MPSII&gt;ai&lt;/MPSII&gt;
        ///  &lt;Yale&gt;ai&lt;/Yale&gt;
        ///  &lt;Tongyong&gt;ai&lt;/Tongyong&gt;
        /// &lt;/item&gt;
        /// &lt;item&gt;
        ///  &lt;Hanyu&gt;an&lt;/Hanyu&gt;
        ///  &lt;Wade&gt;an&lt;/Wade&gt;
        ///  &lt;MPSII&gt;an&lt;/MPSII&gt;
        ///  &lt;Yale&gt;an&lt;/Yale&gt;
        ///  &lt;Tongyong&gt;an&lt;/Tongyong&gt;
        /// &lt;/item&gt;
        /// &lt;item&gt;
        ///  &lt;Hanyu&gt;ang&lt;/Hanyu&gt;
        ///  &lt;Wade&gt;ang&lt;/Wade&gt;
        ///  &lt;MPSII&gt;ang&lt;/MPSII&gt;
        ///  &lt;Yale&gt;ang&lt;/Yale&gt;
        ///  &lt;To [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string pinyin_mapping {
            get {
                return ResourceManager.GetString("pinyin_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3007 (ling2)
        ///4E00 (yi1)
        ///4E01 (ding1,zheng1)
        ///4E02 (kao3)
        ///4E03 (qi1)
        ///4E04 (shang4,shang3)
        ///4E05 (xia4)
        ///4E06 (none0)
        ///4E07 (wan4,mo4)
        ///4E08 (zhang4)
        ///4E09 (san1)
        ///4E0A (shang4,shang3)
        ///4E0B (xia4)
        ///4E0C (ji1)
        ///4E0D (bu4,bu2,fou3)
        ///4E0E (yu3,yu4,yu2)
        ///4E0F (mian3)
        ///4E10 (gai4)
        ///4E11 (chou3)
        ///4E12 (chou3)
        ///4E13 (zhuan1)
        ///4E14 (qie3,ju1)
        ///4E15 (pi1)
        ///4E16 (shi4)
        ///4E17 (shi4)
        ///4E18 (qiu1)
        ///4E19 (bing3)
        ///4E1A (ye4)
        ///4E1B (cong2)
        ///4E1C (dong1)
        ///4E1D (si1)
        ///4E1E (cheng2)
        ///4E1F (diu1)
        ///4E20 (qiu1)
        ///4E21 (liang3) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string unicode_to_hanyu_pinyin {
            get {
                return ResourceManager.GetString("unicode_to_hanyu_pinyin", resourceCulture);
            }
        }
    }
}
